/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as MobcheckRouteImport } from './routes/mobcheck'
import { Route as Mobcheck2RouteImport } from './routes/mobcheck2'
import { Route as Mobcheck3RouteImport } from './routes/mobcheck3'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as ApiEndCallRouteImport } from './routes/api/end-call'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTurnRouteImport } from './routes/api/turn'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MobcheckRoute = MobcheckRouteImport.update({
  id: '/mobcheck',
  path: '/mobcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const Mobcheck2Route = Mobcheck2RouteImport.update({
  id: '/mobcheck2',
  path: '/mobcheck2',
  getParentRoute: () => rootRouteImport,
} as any)
const Mobcheck3Route = Mobcheck3RouteImport.update({
  id: '/mobcheck3',
  path: '/mobcheck3',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiEndCallRoute = ApiEndCallRouteImport.update({
  id: '/api/end-call',
  path: '/api/end-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnRoute = ApiTurnRouteImport.update({
  id: '/api/turn',
  path: '/api/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/mobcheck': typeof MobcheckRoute
  '/mobcheck2': typeof Mobcheck2Route
  '/mobcheck3': typeof Mobcheck3Route
  '/phone': typeof PhoneRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/api/end-call': typeof ApiEndCallRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/turn': typeof ApiTurnRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/mobcheck': typeof MobcheckRoute
  '/mobcheck2': typeof Mobcheck2Route
  '/mobcheck3': typeof Mobcheck3Route
  '/phone': typeof PhoneRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/api/end-call': typeof ApiEndCallRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/turn': typeof ApiTurnRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/mobcheck': typeof MobcheckRoute
  '/mobcheck2': typeof Mobcheck2Route
  '/mobcheck3': typeof Mobcheck3Route
  '/phone': typeof PhoneRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/api/end-call': typeof ApiEndCallRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/turn': typeof ApiTurnRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/mobcheck'
    | '/mobcheck2'
    | '/mobcheck3'
    | '/phone'
    | '/admin'
    | '/analytics'
    | '/leads'
    | '/api/end-call'
    | '/api/stt'
    | '/api/tts'
    | '/api/turn'
    | '/api/public/twilio/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/mobcheck'
    | '/mobcheck2'
    | '/mobcheck3'
    | '/phone'
    | '/admin'
    | '/analytics'
    | '/leads'
    | '/api/end-call'
    | '/api/stt'
    | '/api/tts'
    | '/api/turn'
    | '/api/public/twilio/voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/mobcheck'
    | '/mobcheck2'
    | '/mobcheck3'
    | '/phone'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/leads'
    | '/api/end-call'
    | '/api/stt'
    | '/api/tts'
    | '/api/turn'
    | '/api/public/twilio/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  MobcheckRoute: typeof MobcheckRoute
  Mobcheck2Route: typeof Mobcheck2Route
  Mobcheck3Route: typeof Mobcheck3Route
  PhoneRoute: typeof PhoneRoute
  ApiEndCallRoute: typeof ApiEndCallRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTurnRoute: typeof ApiTurnRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobcheck': {
      id: '/mobcheck'
      path: '/mobcheck'
      fullPath: '/mobcheck'
      preLoaderRoute: typeof MobcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobcheck2': {
      id: '/mobcheck2'
      path: '/mobcheck2'
      fullPath: '/mobcheck2'
      preLoaderRoute: typeof Mobcheck2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobcheck3': {
      id: '/mobcheck3'
      path: '/mobcheck3'
      fullPath: '/mobcheck3'
      preLoaderRoute: typeof Mobcheck3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/end-call': {
      id: '/api/end-call'
      path: '/api/end-call'
      fullPath: '/api/end-call'
      preLoaderRoute: typeof ApiEndCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turn': {
      id: '/api/turn'
      path: '/api/turn'
      fullPath: '/api/turn'
      preLoaderRoute: typeof ApiTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  MobcheckRoute: MobcheckRoute,
  Mobcheck2Route: Mobcheck2Route,
  Mobcheck3Route: Mobcheck3Route,
  PhoneRoute: PhoneRoute,
  ApiEndCallRoute: ApiEndCallRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTurnRoute: ApiTurnRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
